# Generated by Django 5.2.6 on 2025-09-24 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('game_id', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
            ],
            options={
                'db_table': 'games',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('player_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'players',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('team_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'teams',
            },
        ),
        migrations.CreateModel(
            name='Pass',
            fields=[
                ('pass_id', models.IntegerField(primary_key=True, serialize=False)),
                ('completed_pass', models.BooleanField()),
                ('potential_assist', models.BooleanField()),
                ('turnover', models.BooleanField()),
                ('ball_start_loc_x', models.FloatField()),
                ('ball_start_loc_y', models.FloatField()),
                ('ball_end_loc_x', models.FloatField()),
                ('ball_end_loc_y', models.FloatField()),
                ('action_type', models.CharField(choices=[('pickAndRoll', 'Pick and Roll'), ('isolation', 'Isolation'), ('postUp', 'Post Up'), ('offBallScreen', 'Off Ball Screen')], max_length=20)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passes', to='app.game')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passes', to='app.player')),
            ],
            options={
                'db_table': 'passes',
            },
        ),
        migrations.CreateModel(
            name='Shot',
            fields=[
                ('shot_id', models.IntegerField(primary_key=True, serialize=False)),
                ('points', models.IntegerField()),
                ('shooting_foul_drawn', models.BooleanField(default=False)),
                ('shot_loc_x', models.FloatField()),
                ('shot_loc_y', models.FloatField()),
                ('action_type', models.CharField(choices=[('pickAndRoll', 'Pick and Roll'), ('isolation', 'Isolation'), ('postUp', 'Post Up'), ('offBallScreen', 'Off Ball Screen')], max_length=20)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shots', to='app.game')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shots', to='app.player')),
            ],
            options={
                'db_table': 'shots',
            },
        ),
        migrations.AddField(
            model_name='player',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='app.team'),
        ),
        migrations.CreateModel(
            name='Turnover',
            fields=[
                ('turnover_id', models.IntegerField(primary_key=True, serialize=False)),
                ('tov_loc_x', models.FloatField()),
                ('tov_loc_y', models.FloatField()),
                ('action_type', models.CharField(choices=[('pickAndRoll', 'Pick and Roll'), ('isolation', 'Isolation'), ('postUp', 'Post Up'), ('offBallScreen', 'Off Ball Screen')], max_length=20)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turnovers', to='app.game')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turnovers', to='app.player')),
            ],
            options={
                'db_table': 'turnovers',
            },
        ),
    ]
